### ISSUE TITLE
pepr stability

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#102]
An issue to track known errant behavior and workarounds until an upstream fix is available

**Comment by blancharda** [comment]
Occasionally, the pepr watcher pod will stop responding to events and needs to be restarted.

Symptoms include but are not limited to:
* missing or malformed pepr generated resources like virtualservices, exemptions and network policies
* package CRs in a "FAILED" state
* policy enforcement errors

Restarting the pepr watcher pod and impacted deployments tends to resolve the behavior

**Comment by blancharda** [comment]
This has been partially resolved with the introduction of retry logic in `uds-core` 0.22.0 -- however, this issue should remain open until the pepr watch rework is complete.

**Comment by anthonywendt** [comment]
Have a PR to bump uds-core to 0.23.0. This includes some stability and better logging for pepr. Still fighting pepr demons with sso client IDs that stem from things like
- bugs storing the nexus URI clientID in the pepr store. https://github.com/defenseunicorns/uds-core/issues/451
- pepr sidecar termination not working all the time and requiring pepr watcher pod restart. https://github.com/defenseunicorns/uds-core/issues/536

**Comment by anthonywendt** [comment]
Have a new update to the nexus clientID that seems to make the UDS Operartor and Nexus itself happy. This should improve some pepr stability giving pepr something for clientID it can handle better. https://github.com/defenseunicorns/uds-package-nexus/pull/21

**Comment by blancharda** [comment]
Core updates have alleviated much of the behavior..

Closing this issue for now.
If more stability issues pop up, we can open specific issues to track.
