### ISSUE TITLE
Dev env remote state

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#103]
Migrate terraform deploys to utilize remote state.

**Comment by jacobbmay** [comment]
All terraform states have been moved to a Nutanix Objects bucket in the dev environment and IaC deployment repo has been updated to use and store state there. Still need someone else to verify they are able to use it.

**Comment by jacobbmay** [comment]
PR on terraform deployments: https://github.com/defenseunicorns/delivery-nutanix-deployments/pull/6

@anthonywendt has tested the branch and was able to use tofu to run a a plan with the remote state
