### ISSUE TITLE
Pass custom CA chain to gitlab

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#120]
Gitlab is experiencing SSL errors in the prod env. We suspect the cause is gateway certs from a private CA. Adding to the gitlab trust chain should resolve the behavior

**Comment by blancharda** [comment]
Fix is tracked in #118 -- however the issue should remain open until functionality is confirmed

**Comment by jacobbmay** [comment]
Will likely be resolved by #133 currently in progress

**Comment by blancharda** [comment]
resolved
