### ISSUE TITLE
Add support for configuring custom tolerations for different bundle packages

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/uds-bundle-software-factory-nutanix#132]
Related to #131, the bundle should support adding custom tolerations to components that are deployed to control which nodes they run on. For example, if a group of agent nodes are created and tainted specifically for Gitaly, then the GitLab package should support configuring the tolerations needed for Gitaly to deploy to those nodes.

**Comment by JoeHCQ1** [comment]
Done for GitLab, not for others.

**Comment by jacobbmay** [comment]
Gonna close this since Gitaly was the primary need. Can open new ones later if other services end up needing dedicated nodes
