### ISSUE TITLE
Replace dev-redis dependency with valkey

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#135]
We're currently using [a deprecated redis package](https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/blob/main/bundles/uds-core-swf/uds-bundle.yaml#L277) -- we should update this to use the new supported ~redis~ [valkey package](https://github.com/defenseunicorns/uds-package-valkey)

**Comment by JoeHCQ1** [comment]
Found that SWF team was already working this so pairing.

**Comment by blancharda** [comment]
Completed in #146
