### ISSUE TITLE
Add custom CA to neuvector

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#143]
The upstream neuvector chart doesn't directly support extraVolumeMounts. Explore using the custom cert/CA settings to pass our CA.

Alternatively, we may need to issue a PR upstream to enable volume/mounts and/or to pepr to handle the injection automagically.

([more context here](https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/pull/122#issuecomment-2221360670) in #122)

**Comment by JoeHCQ1** [comment]
OBE - neuvector is a rancher product.
