### ISSUE TITLE
Enable, test & document HA Keycloak in bundle

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#148]
Edit
---
See [@jacobbmay's comment](https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/148#issuecomment-2406040129), HA Keycloak should now be enabled by UDS Core. (enable if needed) Test/Verify, Document, & ⛵ it.

Original ticket
---
Autoscaling for keycloak is currently disabled.

Initial attempts at multiple replicas resulted in auth errors (invalid tokens, unexpected prompts to configure MFA for existing users, etc)

**Comment by s-ollek** [comment]
UDS-core owns this currently

**Comment by JoeHCQ1** [comment]
Giving this the ticket-is-bad label because it states a subject alone.

**Comment by jacobbmay** [comment]
This should work now with latest versions of uds-core. I think it was fixed in 25.x of uds-core.

**Comment by JoeHCQ1** [comment]
Will hit this with priority once back
