### ISSUE TITLE
Re-enable confluence

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/uds-bundle-software-factory-nutanix#170]
We will need to add confluence back to the bundle. Ensure the uds package is still up to date before re-enabling in the bundle and update the configuration to accommodate any package changes that have made since we disabled it.

**Comment by JoeHCQ1** [comment]
This may go quite quickly given a working Jira, very similar charts.

**Comment by JoeHCQ1** [comment]
Got it deployed - and updated to the august release.

**Comment by JoeHCQ1** [comment]
https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/pull/193
