### ISSUE TITLE
Investigate HA postgres configuration with NDB

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/uds-bundle-software-factory-nutanix#189]

**Comment by jacobbmay** [comment]
Initial testing with out of box profiles shows it installs multiple postgres instances in a cluster with a separate ha-proxy server for load balancing. It does not configure pgbouncer which is recommended by gitlab for connection pooling for larger architectures so we will probably want to investigate installing that in cluster and configuring it to working with a postgres cluster set up with NDB

**Comment by JoeHCQ1** [comment]
@jacobbmay said the HA tickets are closed so - closing.
