### ISSUE TITLE
Update RKE2 installation instructions

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/uds-bundle-software-factory-nutanix#197]
Make sure RKE2 based installation instructions are up to date and not missing anything.

Currently docs are very spread out and rely on users following a bunch of links. Possibly consolidate into a single start to finish installation guide that starts with IaC and gets through a successful bundle deployment to eliminate steps being missed because someone didn't click on a link to a separate document.

**Comment by JoeHCQ1** [comment]
- We document the needed postgres DBs here: https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/blob/main/docs/database-creation-and-configuration.md
- We document the needed S3 buckets here: https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/blob/main/docs/object-store-creation-and-configuration.md
- Slightly related, the summary SBOM: https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/blob/main/docs/packages-and-dependencies.md
- Verify deployment step: https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/blob/main/docs/verify-deployment.md
- The Nutanix README is probably the main installation doc so far: https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/blob/main/README.md
