### ISSUE TITLE
Add SBOM as release artifact

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#22]
Include the bundle's SBOM(s) as a release artifact

**Comment by JoeHCQ1** [comment]
High priority that the SBOM is included in the bundle, already accomplished. This is about adding a step to the CI pipeline to publish the SBOM with the release bundle so it's available apart from the UDS CLI.

**Comment by MxNxPx** [comment]
addressing via https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/pull/233

**Comment by MxNxPx** [comment]
PR merged, closing complete
