### ISSUE TITLE
Update gitlab package to include OIDC config

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#45]
OIDC config is integrated as of [16.9.1-uds.2](https://github.com/defenseunicorns/uds-package-gitlab/compare/v16.9.1-uds.1...v16.9.1-uds.2) -- we should update at least to here (if not latest)

**Comment by anthonywendt** [comment]
We have updated to [16.10.1-uds.1-registry1](https://github.com/defenseunicorns/uds-package-gitlab/tree/v16.10.1-uds.1)
