### ISSUE TITLE
Nexus SSO Integration

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#47]

**Comment by blancharda** [comment]
Would be resolved by https://github.com/defenseunicorns/uds-core/issues/91

**Comment by anthonywendt** [comment]
> Would be resolved by [defenseunicorns/uds-core#91](https://github.com/defenseunicorns/uds-core/issues/91)

Added this comment to the NeuVector issue. I think it was referenced here by accident?

**Comment by blancharda** [comment]
This may require a license
