### ISSUE TITLE
Document how to integrate Jira with Keycloak

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#48]
This is presumably possible right now. This task primarily consists in two parts:

1. Connect Jira and Keycloak in our deployed dev or test environments.
2. Document how to do it (may reference external docs for the majority of the work but must provide a pointer to users).

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/206
```

**Comment by JoeHCQ1** [comment]
#206 is a subtask.

**Comment by JoeHCQ1** [comment]
Per @jacobbmay we need to:

1. Document that it's not done automatically
2. Point at the upstream docs
