### ISSUE TITLE
Document how to integrate Confluence w/ Keycloak (via Jira)

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#49]
```[tasklist]
### Tasks
- [ ] Get a working sign-in via Keycloak in dev or test
- [ ] Document how to get such a system working (may refer to external docs for heavy lifting)
```

**Comment by JoeHCQ1** [comment]
Here is the ticket tracking Confluence's readiness for UDS: https://github.com/defenseunicorns/uds-package-confluence/issues/6

Will begin picking off tickets there.

**Comment by JoeHCQ1** [comment]
To update: I pushed a lot of the clustering forward here: https://github.com/defenseunicorns/uds-package-confluence/tree/feat-enable-confluence-clustering-by-default.

We / I have more info on how it might be configured to permit Istio. And info to the effect it is possible. That said, this isn't the top priority right now. I'm working more on preparing dashboards (ideally by importing publicly made ones!) into Grafana for onsite support.

**Comment by JoeHCQ1** [comment]
Here is the PR with the work towards clustering: https://github.com/defenseunicorns/uds-package-confluence/pull/46

**Comment by JoeHCQ1** [comment]
Note some of the above comments were out of scope as this ticket was specific to keycloak integration

**Comment by JoeHCQ1** [comment]
Looks like Confluence is as ready as will be: https://github.com/defenseunicorns/uds-package-confluence/issues/6

**Comment by JoeHCQ1** [comment]
Per @jacobbmay we need to:

1. Document that it's not done automatically
2. Point at the upstream docs
