### ISSUE TITLE
Sonarqube

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#51]

**Comment by JoeHCQ1** [comment]
Note that SonarQube is almost ready to be declared "Made for UDS" https://github.com/defenseunicorns/uds-package-sonarqube/issues/99

**Comment by JoeHCQ1** [comment]
@zachariahmiller seems to have a solution near-ready to go for the service monitoring here: https://github.com/defenseunicorns/uds-package-sonarqube/issues/73 -- I'm switching to look at other packages that may need improved.

**Comment by JoeHCQ1** [comment]
SonarQube is now made for UDS: https://github.com/defenseunicorns/uds-package-sonarqube
