### ISSUE TITLE
Explore Nutanix CSI as an alternative to rook-ceph

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#62]
Explore the nutanix CSI as an alternative to Rook-ceph. Establish performance benchmarks (potentially just a targeted GL bench) comparing the two, particularly for large disk sizes.

**Comment by jacobbmay** [comment]
Related PR on uds-rke2-image-builder containing dependencies needed for the nutanix-csi driver to work: https://github.com/defenseunicorns/uds-rke2-image-builder/pull/57

RKE2 cluster must be deployed with an image built from that repo with those changes included

**Comment by jacobbmay** [comment]
Related PR on delivery-nutanix-iac repo to remove secondary drives no longer needed since we switched to nutanix-csi: https://github.com/defenseunicorns/delivery-nutanix-iac/pull/15
