### ISSUE TITLE
Establish a targeted update cadence

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#63]
It will be untenable to update the overall bundle on the update or release of each sub-package. We should establish a bi-weekly (or other regular) release cycle which includes all available and tested updates.

Obviously this would exclude hotfixes and high priority security patches.

**Comment by anthonywendt** [comment]
We have talked about maybe once a week? Wednesday nights?

**Comment by blancharda** [comment]
Once a week seems reasonable while we wrap up the initial capability. We may want to drop that to every other week once things stabilize a bit more.

**Comment by blancharda** [comment]
After chats on the side, we are in agreement (and have tentatively communicated) that we will be targeting a weekly Wednesday update as we continue to work through features and fixes.
