### ISSUE TITLE
Nexus stuck initializing

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#66]
Investigate potential FIPS issue

**Comment by blancharda** [comment]
When accessing the UI, it appears to be stuck initializing as shown below.
Logs indicate a file-not-found exception
![image](https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/assets/9499393/7e63163a-dcac-48b4-849e-4b726e38c37a)

**Comment by anthonywendt** [comment]
Fix brought in with this PR: https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/pull/77/files
