### ISSUE TITLE
Gitlab Web IDE 

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#71]
Gitlab web IDE appears non-functional.
Investigate and debug.

**Comment by blancharda** [comment]
Worth double checking network policies for the gitlab-shell pod

**Comment by blancharda** [comment]
May be related to https://github.com/defenseunicorns/uds-core/issues/288

**Comment by anthonywendt** [comment]
Merged in new uds-core version which fixed this here: https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/pull/83
