### ISSUE TITLE
Mattermost Plugins

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#72]
Mattermost plugins appear to fail install.
(May be related to storage?)

**Comment by anthonywendt** [comment]
Plugins now install and startup. Fix merged with https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/pull/81. Plugin fix only required the object storage region which wasn't being set right and causing this issue. But also added the ability to provide additional CA certs to trust.

We may need more individual plugin work like in #73 where I mention we may need to install another chart for that plugin to work.

Before mattermost object store fix
![Image](https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/assets/30995023/ee1c2c6d-1916-4c6d-ab01-b2eebebe5d89)

After mattermost object store fix
![Image](https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/assets/30995023/e8b24058-4bc0-45ae-b05b-5ddd9a1e881e)
