### ISSUE TITLE
Unable to sign out of grafana

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#95]
After logging into grafana via SSO, there does not appear to be a way to log out.

**Comment by blancharda** [comment]
I have been unable to reproduce this behavior on the current WIP release -- it's possible this may have been resolved as part of the update that fixed SSO for gitlab 🤔

Reaching out for more context from the original reporter before we close the issue.

**Comment by blancharda** [comment]
I believe the missing custom CA trust was preventing us from reproducing the error.

Now we are seeing the same behavior in dev.

Should be resolved in https://github.com/defenseunicorns/uds-core/pull/559

**Comment by s-ollek** [comment]
closing
